language: node_js
sudo: false
node_js:
  - "7.9"
install:
  - npm install
script:
  - npm test
notifications:
  irc:
    channels:
      - "irc.esper.net#CodeAgainstAManatee"
    on_success: change
    on_failure: always
    template:
      - "%{repository_name}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
